<?php
  $ConstantsArray = array('dbServerUrl' => '/Applications/XAMPP/xamppfiles/htdocs/dinner/'
    ,'imagefolderpath' => '/Applications/XAMPP/xamppfiles/htdocs/dinner/images/'
    ,'docspath' => '/Applications/XAMPP/xamppfiles/htdocs/dinner/docs/'
    ,'ImagePath' => '/Applications/XAMPP/xamppfiles/htdocs/dinner/Images/AdminImages/'
  	,'BadgeImagePath' => '/Applications/XAMPP/xamppfiles/htdocs/dinner/images/AdminImages/BadgeImages/'	
    ,'UserImagePath' => '/Applications/XAMPP/xamppfiles/htdocs/dinner/Images/UserImages/'
  	,'CompanyImagePath' => '/Applications/XAMPP/xamppfiles/htdocs/dinner/Images/CompanyImages/'
  	,'CompanyImageURL' => 'http://localhost/dinner/Images/CompanyImages/'
    ,'UserCertificatePath' => '/Applications/XAMPP/xamppfiles/htdocs/dinner/Images/UserCertificates/')
  ;
  $ConstantsArray['ApplicationURL'] = "http://localhost/dinner/";

  $ConstantsArray["CUSTOM_FIELD_PREFIX"]  = "cus_";
  //$ConstantsArray = array('dbServerUrl' => '/home/satyain/public_html/giftcard/');
  //Logger::configure($ConstantsArray['dbServerUrl'] .'log4php/log4php.xml');
  $ConstantsArray['ApplicationURL'] = "http://localhost/dinner";
  $Log4PHP_MyDBLogger = "myDBLogger";
  $Log4PHP_MyMailerLogger = "myMailerLogger";
  $Log4PHP_MyFileLogger = "myFileLogger";
  $CUSTOM_FIELD_PREFIX = "cus_"

?>